services:
    php:
        build:
            context: ./.docker
            args:
                uid: ${UID:-1000}
        ports:
            - 8888:80
        depends_on:
            - mysql
            - node
            - traefik
        environment:
            - APACHE_RUN_USER=#1000
            - APACHE_RUN_GROUP=#1000
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.php.rule=Host(`test-docker.localhost`)"
        volumes:
            - ./:/var/www/html
        networks:
            - internalnetworktest

    mysql:
        image: mysql:8.0.35
        restart: always
        tty: true
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
            interval: 5s
            timeout: 5s
            retries: 20
        ports:
            - 33092:3306
        networks:
            - internalnetworktest

    node:
        image: node:21.7.1-alpine
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - 5193:5173
        networks:
            - internalnetworktest

    traefik:
        image: traefik:v2.11
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        networks:
            - internalnetworktest

networks:
    internalnetworktest:
