services:
    php:
        build:
            context: .
            args:
                uid: ${UID:-1000}
        ports:
            - 8888:80
        environment:
            - APACHE_RUN_USER=#1000
            - APACHE_RUN_GROUP=#1000
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.php.rule=Host(`test-docker.localhost`)"
        volumes:
            - ./:/var/www/html
        networks:
            - internalnetworktest
        depends_on:
            - mysql
            - node
            - traefik

    mysql:
        image: mysql/mysql-server:8.0
        ports:
            - 33092:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - internalnetworktest
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

    node:
        image: node:21.7.1-alpine
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - 5193:5173
        networks:
            - internalnetworktest

    traefik:
        image: traefik:v2.11
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        networks:
            - internalnetworktest

networks:
    internalnetworktest:

volumes:
    mysql_data:
        driver: local
